### ISSUE TITLE
Handling expired PubSub tokens

### ISSUE THREAD

**Issue by POD666** [sagi/workers-pubsub#17]
I'm a bit concerned that GCP token that is retrieved during PubSubREST initialization might get expired.

I see no handling for this in the `publish` function. 
I've just reviewed the code, so maybe I get something wrong and it never happens.

How would you suggest handling it in production? 

For now, I just init PubSubREST client on each request which is obviously not good enough.

**Comment by POD666** [comment]
Hmm, looks like the Q is bigger than I thought originally.

Let's redefine the Q: how to avoid retrieving GCP tokens on each request?

Using [Durable Objects](https://developers.cloudflare.com/workers/learning/using-durable-objects/) seems to be a possible solution. Another solution that I'm thinking about is to store GCP tokens in [KV](https://developers.cloudflare.com/workers/runtime-apis/kv/) with expiration and make the PubSubREST get tokens from there and only send requests for a new GCP token if no token in KV.

Feels like I miss something 😅

What do you think?

**Comment by sagi** [comment]
Hey there!

This library uses [workers-jwt](https://github.com/sagi/workers-jwt) underneath, which means that each time  `PubSubREST` is instantiated, a valid `token` is generated "offline" (and not retrieved) via the given `GCP` Service Account, avoiding any round trips to GCP.

This way, you don't need to cache any tokens - they are simply generated out of a valid `GCP` service account - which is perfect for serverless architectures, because it avoids any caching and saves a round trip.

I use it in production with [AnonymityBot](https://anonymitybot.com) and it works great.

Stay safe
